// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMnPjXT52frQd5z2qeC5eFoFLcKj2mCgE',
    appId: '1:1096967124531:ios:6808a9a1abd68449a39546',
    messagingSenderId: '1096967124531',
    projectId: 'newchatify-ba89a',
    storageBucket: 'newchatify-ba89a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMnPjXT52frQd5z2qeC5eFoFLcKj2mCgE',
    appId: '1:1096967124531:ios:6808a9a1abd68449a39546',
    messagingSenderId: '1096967124531',
    projectId: 'newchatify-ba89a',
    storageBucket: 'newchatify-ba89a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcsFoI_aAQd7eDCtDQoBEq6EJBbr4ZBww',
    appId: '1:1096967124531:web:2d6b603b4fad9c02a39546',
    messagingSenderId: '1096967124531',
    projectId: 'newchatify-ba89a',
    authDomain: 'newchatify-ba89a.firebaseapp.com',
    storageBucket: 'newchatify-ba89a.firebasestorage.app',
    measurementId: 'G-0K133WLKX3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcsFoI_aAQd7eDCtDQoBEq6EJBbr4ZBww',
    appId: '1:1096967124531:web:2d6b603b4fad9c02a39546',
    messagingSenderId: '1096967124531',
    projectId: 'newchatify-ba89a',
    authDomain: 'newchatify-ba89a.firebaseapp.com',
    storageBucket: 'newchatify-ba89a.firebasestorage.app',
    measurementId: 'G-0K133WLKX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuuzWIGI4BDvNTG4XKn2vCG9yVMj4Cjw',
    appId: '1:1096967124531:android:bd4ae0ce1f058fe4a39546',
    messagingSenderId: '1096967124531',
    projectId: 'newchatify-ba89a',
    storageBucket: 'newchatify-ba89a.firebasestorage.app',
  );

}