import 'package:flutter/material.dart';

// Firebase Packages
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:provider/provider.dart';

// Firebase options (generated by flutterfire configure)
import 'firebase_options.dart';

// Providers
import './providers/authentication_provider.dart';

// Services
import './services/navigation_service.dart';

// Pages
import './pages/splash_page.dart';
import './pages/login_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // works for Android + Web
  );
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _initialized = false;
  late FirebaseAnalytics analytics;

  @override
  void initState() {
    super.initState();
    _setup();
  }

  Future<void> _setup() async {
    // Firebase Analytics instance (optional)
    analytics = FirebaseAnalytics.instance;

    // Fake splash delay
    await Future.delayed(const Duration(seconds: 1));
    setState(() {
      _initialized = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AuthenticationProvider>(
          create: (_) => AuthenticationProvider(),
        ),
      ],
      child: MaterialApp(
        title: 'Chatify',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          scaffoldBackgroundColor: const Color.fromARGB(255, 50, 48, 75),
          bottomNavigationBarTheme: const BottomNavigationBarThemeData(
            backgroundColor: Color.fromRGBO(30, 29, 37, 1.0),
          ),
        ),
        navigatorKey: NavigationService.navigatorKey, // ✅ Static key
        initialRoute: '/login',
        routes: {
          '/login': (_) => LoginPage(),
        },
      ),
    );
  }
}
