import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';

// Firebase Packages
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:provider/provider.dart';

// Firebase options (generated by flutterfire configure)
import 'firebase_options.dart';

// Providers
import './providers/authentication_provider.dart';

// Services
import './services/navigation_service.dart';
import './services/media_service.dart';
import './services/database_service.dart';
import './services/cloud_storage_service.dart';

// Pages
import './pages/splash_page.dart';
import './pages/login_page.dart';
import './pages/register_page.dart';
import './pages/home_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  _setupServices();
  runApp(MyApp());
}

void _setupServices() {
  GetIt.instance.registerSingleton<NavigationService>(NavigationService());
  GetIt.instance.registerSingleton<MediaService>(MediaService());
  GetIt.instance.registerSingleton<DatabaseService>(DatabaseService());
  GetIt.instance.registerSingleton<CloudStorageService>(CloudStorageService());
}

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _initialized = false;
  late FirebaseAnalytics analytics;

  @override
  void initState() {
    super.initState();
    _setup();
  }

  Future<void> _setup() async {
    analytics = FirebaseAnalytics.instance;
    await Future.delayed(const Duration(seconds: 1));
    setState(() {
      _initialized = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AuthenticationProvider>(
          create: (_) => AuthenticationProvider(),
        ),
      ],
      child: MaterialApp(
        title: 'Chatify',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          scaffoldBackgroundColor: const Color.fromARGB(255, 50, 48, 75),
          bottomNavigationBarTheme: const BottomNavigationBarThemeData(
            backgroundColor: Color.fromRGBO(30, 29, 37, 1.0),
          ),
        ),
        navigatorKey: NavigationService.navigatorKey,
        initialRoute: '/login',
        routes: {
          '/login': (BuildContext _context) => LoginPage(),
          '/register': (BuildContext _context) => RegisterPage(),
          '/home': (BuildContext _context) => HomePage(),
        },
      ),
    );
  }
}
